# Generated by Django 2.1.5 on 2019-01-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=15)),
                ('data_nascimento', models.CharField(max_length=10)),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=10)),
                ('barrio', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=100)),
                ('numero_celular', models.CharField(max_length=20)),
            ],
        ),
    ]
