# Generated by Django 2.1.5 on 2019-01-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpoint', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CadastroCliente',
            new_name='ConsultaCliente',
        ),
    ]
